
DROP TABLE IF EXISTS dbo.Usuario
CREATE TABLE dbo.Usuario (
    idUsuario INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	idPersona INT FOREIGN KEY REFERENCES Persona(idPersona) NOT NULL,
    NombreUsuario VARCHAR(75) NOT NULL,
    Contrasenha VARCHAR(75) NOT NULL,
	Nivel VARCHAR(75) NOT NULL,
	Estado VARCHAR(75) NOT NULL
);
